### ISSUE TITLE
SADXLVL2 crashes when trying to load Autodemo Windy Valley

### ISSUE THREAD

**Issue by GamecubeGuy** [sonicretro/sa_tools#156]
I'm trying to load Autodemo Windy Valley in SADXLVL2 but it keeps giving me an error message and crashes.

Error messgae:
Program: SADXLVL2
Build Date: 03/05/2021 06:06:40
OS Version: Microsoft Windows NT 10.0.18363.0
Log:
SharpDX.SharpDXException: HRESULT: [0x8876086C], Module: [SharpDX.Direct3D9], ApiCode: [D3DERR_INVALIDCALL/InvalidCall], Message: Unknown
   at SharpDX.Result.CheckError() in C:\projects\sharpdx\Source\SharpDX\Result.cs:line 195
   at SharpDX.Direct3D9.Device.CreateTexture(Int32 width, Int32 height, Int32 levels, Int32 usage, Format format, Pool pool, Texture textureOut, IntPtr sharedHandleRef) in C:\projects\sharpdx\Source\SharpDX.Direct3D9\Generated\Interfaces.cs:line 5089
   at SharpDX.Direct3D9.Texture..ctor(Device device, Int32 width, Int32 height, Int32 levelCount, Usage usage, Format format, Pool pool) in C:\projects\sharpdx\Source\SharpDX.Direct3D9\Texture.cs:line 44
   at SADXObjectDefinitions.Common.PUWind.Render(SETItem item, Device dev, EditorCamera camera, MatrixStack transform) in c:\Users\Michael\Downloads\Sonic Adventure DX\Projects\AutoDemo-Project_SADXLVL2-master\objdefs\Common\PUWind.cs:line 45
   at SonicRetro.SAModel.SAEditorCommon.DataTypes.SETItem.Render(Device dev, EditorCamera camera, MatrixStack transform) in D:\Programs\sa_tools\SAEditorCommon\DataTypes\SETItem.cs:line 139
   at SonicRetro.SAModel.SADXLVL2.MainForm.DrawLevel() in D:\Programs\sa_tools\SADXLVL2\MainForm.cs:line 1684
   at SonicRetro.SAModel.SADXLVL2.MainForm.panel1_Paint(Object sender, PaintEventArgs e) in D:\Programs\sa_tools\SADXLVL2\MainForm.cs:line 1804
   at System.Windows.Forms.Control.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.UserControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by PiKeyAr** [comment]
The object definition for PUWind in your installation isn't compatible with the current version of SADXLVL2. If you want to use object definitions, you need to replace yours with the newer ones included in the latest version of SA Tools.

**Comment by GamecubeGuy** [comment]
Okay, how do I do that?

**Comment by PiKeyAr** [comment]
You need to replace the objdefs folder in your project folder.

**Comment by GamecubeGuy** [comment]
I replaced the objdefs folder with the current one but I'm still getting the same error.
![image](https://user-images.githubusercontent.com/31381571/110797376-039f6a00-8247-11eb-8a2b-5e8ce50e16e9.png)
Error:
Program: SADXLVL2
Build Date: 03/05/2021 06:06:40
OS Version: Microsoft Windows NT 10.0.18363.0
Log:
SharpDX.SharpDXException: HRESULT: [0x8876086C], Module: [SharpDX.Direct3D9], ApiCode: [D3DERR_INVALIDCALL/InvalidCall], Message: Unknown
   at SharpDX.Result.CheckError() in C:\projects\sharpdx\Source\SharpDX\Result.cs:line 195
   at SharpDX.Direct3D9.Device.CreateTexture(Int32 width, Int32 height, Int32 levels, Int32 usage, Format format, Pool pool, Texture textureOut, IntPtr sharedHandleRef) in C:\projects\sharpdx\Source\SharpDX.Direct3D9\Generated\Interfaces.cs:line 5089
   at SharpDX.Direct3D9.Texture..ctor(Device device, Int32 width, Int32 height, Int32 levelCount, Usage usage, Format format, Pool pool) in C:\projects\sharpdx\Source\SharpDX.Direct3D9\Texture.cs:line 44
   at SADXObjectDefinitions.Common.PUWind.Render(SETItem item, Device dev, EditorCamera camera, MatrixStack transform) in c:\Users\Michael\Downloads\Sonic Adventure DX\Projects\AutoDemo-Project_SADXLVL2-master\objdefs\Common\PUWind.cs:line 45
   at SonicRetro.SAModel.SAEditorCommon.DataTypes.SETItem.Render(Device dev, EditorCamera camera, MatrixStack transform) in D:\Programs\sa_tools\SAEditorCommon\DataTypes\SETItem.cs:line 139
   at SonicRetro.SAModel.SADXLVL2.MainForm.DrawLevel() in D:\Programs\sa_tools\SADXLVL2\MainForm.cs:line 1684
   at SonicRetro.SAModel.SADXLVL2.MainForm.panel1_Paint(Object sender, PaintEventArgs e) in D:\Programs\sa_tools\SADXLVL2\MainForm.cs:line 1804
   at System.Windows.Forms.Control.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.UserControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by PiKeyAr** [comment]
Try deleting the dllcache folder in the project folder, it probably still has the old object definition DLL file.

**Comment by GamecubeGuy** [comment]
I can't find the dllcache folder.
![image](https://user-images.githubusercontent.com/31381571/110799581-4f531300-8249-11eb-9733-ba408c44422c.png)

**Comment by PiKeyAr** [comment]
It's a hidden folder. If you still can't find it, you could make a new project and replace the files in it with the files from your current project.

**Comment by GamecubeGuy** [comment]
Deleting the dllcache folder worked, thank you.
