### ISSUE TITLE
Emerald Coast 2 crashed for some reason

### ISSUE THREAD

**Issue by GamecubeGuy** [sonicretro/sa_tools#161]
I opened Emerald Coast 2, and I got this error. I added objects, but I'm not sure which object made it crash.

Program: SADXLVL2
Build Date: 03/24/2021 04:08:21
OS Version: Microsoft Windows NT 10.0.19042.0
Log:
SharpDX.SharpDXException: HRESULT: [0x8876086C], Module: [SharpDX.Direct3D9], ApiCode: [D3DERR_INVALIDCALL/InvalidCall], Message: Unknown
   at SharpDX.Result.CheckError() in C:\projects\sharpdx\Source\SharpDX\Result.cs:line 195
   at SharpDX.Direct3D9.Device.CreateTexture(Int32 width, Int32 height, Int32 levels, Int32 usage, Format format, Pool pool, Texture textureOut, IntPtr sharedHandleRef) in C:\projects\sharpdx\Source\SharpDX.Direct3D9\Generated\Interfaces.cs:line 5084
   at SharpDX.Direct3D9.Texture..ctor(Device device, Int32 width, Int32 height, Int32 levelCount, Usage usage, Format format, Pool pool) in C:\projects\sharpdx\Source\SharpDX.Direct3D9\Texture.cs:line 45
   at SADXObjectDefinitions.EmeraldCoast.OBEWind.Render(SETItem item, Device dev, EditorCamera camera, MatrixStack transform) in c:\Users\Michael\Downloads\Sonic Adventure DX\Projects\test\objdefs\Emerald Coast\O BEWIND.cs:line 82
   at SonicRetro.SAModel.SAEditorCommon.DataTypes.SETItem.Render(Device dev, EditorCamera camera, MatrixStack transform) in D:\Programs\sa_tools\SAEditorCommon\DataTypes\SETItem.cs:line 141
   at SonicRetro.SAModel.SADXLVL2.MainForm.DrawLevel() in D:\Programs\sa_tools\SADXLVL2\MainForm.cs:line 1733
   at System.Windows.Forms.Control.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.UserControl.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by PiKeyAr** [comment]
Same issue as #156. Upgrade object definitions (there's an automated way to do that in the Edit>Debug menu) or recreate the project with Project Manager.

**Comment by GamecubeGuy** [comment]
Thank you.
