### ISSUE TITLE
SAMDL crashes when I try to load SA2 character textures

### ISSUE THREAD

**Issue by TeridaxXD001** [sonicretro/sa_tools#168]
I loaded the Tails model and then tried to load the texture. I get an EndOfStreamException with the following:
Program: SAMDL
Build Date: 03/05/2021 06:06:41
OS Version: Microsoft Windows NT 10.0.19041.0
Log:
SAMDL: New log entry on 6/4/2021 12:47:33 AM

System.IO.EndOfStreamException: Attempted to read past the end of the stream.
   at PuyoTools.Modules.PTStream.ReadByte(Stream source)
   at PuyoTools.Modules.PTStream.ReadInt32(Stream source)
   at PuyoTools.Modules.Archive.GvmArchiveReader..ctor(Stream source)
   at PuyoTools.Modules.Archive.GvmArchive.Open(Stream source)
   at PuyoTools.Modules.Archive.ArchiveBase.Open(Byte[] source, Int32 offset, Int32 length)
   at SonicRetro.SAModel.Direct3D.TextureSystem.TextureArchive.GetTextures(String filename) in D:\Programs\sa_tools\SAModel.Direct3D\TextureSystem\TextureArchive.cs:line 33
   at SonicRetro.SAModel.SAMDL.MainForm.LoadTextures(String filename) in D:\Programs\sa_tools\SAMDL\MainForm.cs:line 1772
   at SonicRetro.SAModel.SAMDL.MainForm.loadTexturesToolStripMenuItem_Click(Object sender, EventArgs e) in D:\Programs\sa_tools\SAMDL\MainForm.cs:line 1789
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by TeridaxXD001** [comment]
I'm an IDIOT...
