### ISSUE TITLE
SALVL crash on exit

### ISSUE THREAD

**Issue by PiKeyAr** [sonicretro/sa_tools#21]
Every time I exit SALVL it crashes.
![image](https://user-images.githubusercontent.com/23312549/42793698-55f0e518-89b6-11e8-9036-4fe2f772fc29.png)
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.DirectX.Direct3D.Font.OnLostDevice()
   at Microsoft.DirectX.Direct3D.Font.OnParentLost(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at Microsoft.DirectX.Direct3D.Device.raise_DeviceLost(Object i1, EventArgs i2)
   at Microsoft.DirectX.Direct3D.Device.Finalize()
```

**Comment by jcorvinus** [comment]
Fixed in branch 3d_Editor_UI_Improvements, commit: 42cab37646bbf8b52cfdd5221b807e31fc4e491d

It'll be merged into master when the next batch of editor improvements is ready.
