### ISSUE TITLE
SADXLVL2 Import Issue

### ISSUE THREAD

**Issue by Shadowth117** [sonicretro/sa_tools#30]
SADXLVL2 is having problems when importing this after clicking anywhere in the viewport:
[ParallelTundraGarden.zip](https://github.com/sonicretro/sa_tools/files/2637564/ParallelTundraGarden.zip)

and it seems to be related to polygons counts. Occurs with straight obj importing as well as nodetable. Older versions, I believe before the project update, but at least as recent as April 8th 2018 imported this same thing fine. However when trying to load up this sa1lvl in the new build, the same errors that come up when clicking the viewport after importing through that version come up. 

Said error is:
Program: SADXLVL2
Build Date: 10/07/2018 04:56:37
OS Version: Microsoft Windows NT 6.2.9200.0
Log:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at SonicRetro.SAModel.Direct3D.Mesh`1.CheckHit(Vector3 Near, Vector3 Far, Viewport Viewport, Matrix Projection, Matrix View, Matrix transform, NJS_OBJECT model) in E:\AutoBuild\sa_tools\SAModel.Direct3D\Mesh.cs:line 350
   at SonicRetro.SAModel.SAEditorCommon.DataTypes.LevelItem.CheckHit(Vector3 Near, Vector3 Far, Viewport Viewport, Matrix Projection, Matrix View) in E:\AutoBuild\sa_tools\SAEditorCommon\DataTypes\LevelItem.cs:line 121
   at SonicRetro.SAModel.SADXLVL2.MainForm.PickItem(Point mouse, Item& item) in E:\AutoBuild\sa_tools\SADXLVL2\MainForm.cs:line 2253
   at SonicRetro.SAModel.SADXLVL2.MainForm.panel1_MouseDown(Object sender, MouseEventArgs e) in E:\AutoBuild\sa_tools\SADXLVL2\MainForm.cs:line 2160
   at System.Windows.Forms.Control.OnMouseDown(MouseEventArgs e)
   at System.Windows.Forms.UserControl.OnMouseDown(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.UserControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Shadowth117** [comment]
-A link to the landtable in question [can be found here](https://1drv.ms/u/s!AmsmLjy_fwAMgdFUfXTBjPv4DpsgUg)

I did a new import with meshes with smaller polycounts, roughly 5kish. This prevents the above endless errors, but brings up new issues. The ingame look is the same as the above where mat colors appear black. However in editor, duplicating meshes or opening the material editor causes errors. The immediate below error occurs for both cases. It continues into the editor if continue is pressed, however the material appears blank. You can edit this to tweak the material and it seems to work, but none of the current settings are loaded meaning they must ALL be set by hand again.

Program: SADXLVL2
Build Date: 12/04/2018 02:43:35
OS Version: Microsoft Windows NT 6.2.9200.0
Log:
System.NullReferenceException: Object reference not set to an instance of an object.
   at SonicRetro.SAModel.SAEditorCommon.UI.SceneGraphControl.LoadFullTree() in E:\AutoBuild\sa_tools\SAEditorCommon\UI\SceneGraphControl.cs:line 203
   at SonicRetro.SAModel.SAEditorCommon.UI.SceneGraphControl.LevelData_StateChanged() in E:\AutoBuild\sa_tools\SAEditorCommon\UI\SceneGraphControl.cs:line 183
   at System.Action.Invoke()
   at SonicRetro.SAModel.SAEditorCommon.DataTypes.LevelData.InvalidateRenderState() in E:\AutoBuild\sa_tools\SAEditorCommon\DataTypes\LevelData.cs:line 144
   at SonicRetro.SAModel.SAEditorCommon.DataTypes.LevelItem.pw_FormUpdated(Object sender, EventArgs e) in E:\AutoBuild\sa_tools\SAEditorCommon\DataTypes\LevelItem.cs:line 284
   at SonicRetro.SAModel.SAEditorCommon.UI.MaterialEditor.RaiseFormUpdated() in E:\AutoBuild\sa_tools\SAEditorCommon\UI\MaterialEditor.cs:line 260
   at SonicRetro.SAModel.SAEditorCommon.UI.MaterialEditor.alphaDiffuseNumeric_ValueChanged(Object sender, EventArgs e) in E:\AutoBuild\sa_tools\SAEditorCommon\UI\MaterialEditor.cs:line 147
   at System.Windows.Forms.NumericUpDown.OnValueChanged(EventArgs e)
   at System.Windows.Forms.NumericUpDown.set_Value(Decimal value)
   at SonicRetro.SAModel.SAEditorCommon.UI.MaterialEditor.SetControls(Int32 index) in E:\AutoBuild\sa_tools\SAEditorCommon\UI\MaterialEditor.cs:line 45
   at SonicRetro.SAModel.SAEditorCommon.UI.MaterialEditor.comboMaterial_SelectedIndexChanged(Object sender, EventArgs e) in E:\AutoBuild\sa_tools\SAEditorCommon\UI\MaterialEditor.cs:line 76
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   at SonicRetro.SAModel.SAEditorCommon.UI.MaterialEditor.MaterialEditor_Load(Object sender, EventArgs e) in E:\AutoBuild\sa_tools\SAEditorCommon\UI\MaterialEditor.cs:line 33
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
