### ISSUE TITLE
SADXLVL2 Problem

### ISSUE THREAD

**Issue by fancythedeveloper** [sonicretro/sa_tools#42]
I'm trying to import my OBJ over Emerald Coast 1 but I keep getting an error.

`Program: SADXLVL2
Build Date: 05/08/2019 18:23:56
OS Version: Microsoft Windows NT 6.2.9200.0
Log:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at SonicRetro.SAModel.Direct3D.Extensions.obj2nj(String objfile, String[] textures) in E:\Programs\sa_tools\SAModel.Direct3D\Extensions.cs:line 991
   at SonicRetro.SAModel.SAEditorCommon.DataTypes.LevelItem.ImportModel(String filePath) in E:\Programs\sa_tools\SAEditorCommon\DataTypes\LevelItem.cs:line 156
   at SonicRetro.SAModel.SAEditorCommon.DataTypes.LevelItem..ctor(String filePath, Vertex position, Rotation rotation, Int32 index, EditorItemSelection selectionManager) in E:\Programs\sa_tools\SAEditorCommon\DataTypes\LevelItem.cs:line 46
   at SonicRetro.SAModel.SAEditorCommon.DataTypes.LevelData.ImportFromFile(String filePath, EditorCamera camera, Boolean& errorFlag, String& errorMsg, EditorItemSelection selectionManager) in E:\Programs\sa_tools\SAEditorCommon\DataTypes\LevelData.cs:line 418
   at SonicRetro.SAModel.SADXLVL2.MainForm.ImportToStage() in E:\Programs\sa_tools\SADXLVL2\MainForm.cs:line 2781
   at SonicRetro.SAModel.SADXLVL2.MainForm.toStageToolStripMenuItem_Click(Object sender, EventArgs e) in E:\Programs\sa_tools\SADXLVL2\MainForm.cs:line 2753
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
`

[Stage mod.zip](https://github.com/sonicretro/sa_tools/files/3168686/Stage.mod.zip)
^ (My stage's OBJ, can send SKP if needed)

**Comment by jcorvinus** [comment]
The stage mod zip file doesn't appear to have an mtl file - that might be causing problems. The obj file does reference a non-present material file. Although what's confusing me is that the code in Extensions.cs, 991 shouldn't be capable of throwing IndexOutOfRangeException

**Comment by fancymelonub** [comment]
Oh, the mtl file has a _ while the obj does not, I'll try again with the OBJ having the _

**Comment by fancymelonub** [comment]
I got something similar even though the OBJ and the MTL are named the same.

`Program: SADXLVL2
Build Date: 05/08/2019 18:23:56
OS Version: Microsoft Windows NT 6.2.9200.0
Log:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at SonicRetro.SAModel.Direct3D.Extensions.obj2nj(String objfile, String[] textures) in E:\Programs\sa_tools\SAModel.Direct3D\Extensions.cs:line 991
   at SonicRetro.SAModel.SAEditorCommon.DataTypes.LevelItem.ImportModel(String filePath) in E:\Programs\sa_tools\SAEditorCommon\DataTypes\LevelItem.cs:line 156
   at SonicRetro.SAModel.SAEditorCommon.DataTypes.LevelItem..ctor(String filePath, Vertex position, Rotation rotation, Int32 index, EditorItemSelection selectionManager) in E:\Programs\sa_tools\SAEditorCommon\DataTypes\LevelItem.cs:line 46
   at SonicRetro.SAModel.SAEditorCommon.DataTypes.LevelData.ImportFromFile(String filePath, EditorCamera camera, Boolean& errorFlag, String& errorMsg, EditorItemSelection selectionManager) in E:\Programs\sa_tools\SAEditorCommon\DataTypes\LevelData.cs:line 418
   at SonicRetro.SAModel.SADXLVL2.MainForm.ImportToStage() in E:\Programs\sa_tools\SADXLVL2\MainForm.cs:line 2781
   at SonicRetro.SAModel.SADXLVL2.MainForm.toStageToolStripMenuItem_Click(Object sender, EventArgs e) in E:\Programs\sa_tools\SADXLVL2\MainForm.cs:line 2753
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)'

[Stage mod.zip](https://github.com/sonicretro/sa_tools/files/3169702/Stage.mod.zip)
^ (This includes not only the OBJ, but the MTL, and the original SKP/SKB)

**Comment by PiKeyAr** [comment]
3 years late, but both of the files you shared should import fine in SADXLVL2 now.

**Comment by fancythedeveloper** [comment]
Cool! I'm not really into SADX anymore, but I'll definitely give it a go!
