### ISSUE TITLE
Are some SET Items out of range in certain levels or something?

### ISSUE THREAD

**Issue by BCMediaPlayer** [sonicretro/sa_tools#60]
Still working to delete certain SET objects in all the levels, and in stages like the bosses, Ice Cap, or the pinball areas, I get this notification and either can't delete them, or have to find them on the map and manually remove them instead of wipe them from the SET object list, which doesn't exist.
![bandicam 2019-11-05 16-49-14-680](https://user-images.githubusercontent.com/57376112/68258727-7c0b7080-ffec-11e9-9e5a-26f57e0479c5.png)

**Comment by MainMemory** [comment]
Can you be more specific about what you did? Also, in the future you should click the Report button and paste what's in there on here.

**Comment by BCMediaPlayer** [comment]
Well, when I click a level like Chaos 0 or Casinopolis Act 3 (Sonic-themed Pinball stage), I get this notification.
![bandicam 2019-11-06 07-25-17-893](https://user-images.githubusercontent.com/57376112/68311802-f1b42280-0066-11ea-870f-403f58e9c2bb.png)
Then, when I try to select a ring or item box, I get the notification from the first message.

**Comment by MainMemory** [comment]
Did you not read what I wrote last time?

**Comment by BCMediaPlayer** [comment]
You told me to be more specific.

**Comment by MainMemory** [comment]
I told you to post the details you get from clicking the "Report" button.

**Comment by BCMediaPlayer** [comment]
Oh, you mean this stuff?
Program: SADXLVL2
Build Date: 07/21/2019 22:31:43
OS Version: Microsoft Windows NT 6.2.9200.0
Log:
System.NullReferenceException: Object reference not set to an instance of an object.
   at SonicRetro.SAModel.SAEditorCommon.UI.SceneGraphControl.LoadFullTree() in E:\Programs\sa_tools\SAEditorCommon\UI\SceneGraphControl.cs:line 203
   at SonicRetro.SAModel.SAEditorCommon.UI.SceneGraphControl.LevelData_StateChanged() in E:\Programs\sa_tools\SAEditorCommon\UI\SceneGraphControl.cs:line 183
   at System.Action.Invoke()
   at SonicRetro.SAModel.SAEditorCommon.DataTypes.LevelData.InvalidateRenderState() in E:\Programs\sa_tools\SAEditorCommon\DataTypes\LevelData.cs:line 144
   at SonicRetro.SAModel.SADXLVL2.MainForm.backgroundWorker1_RunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs e) in E:\Programs\sa_tools\SADXLVL2\MainForm.cs:line 1522
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.AsyncOperationCompleted(Object arg)

**Comment by MainMemory** [comment]
You're using an outdated version of SA Tools. I'm pretty sure I already fixed this.

**Comment by MainMemory** [comment]
Closing because I'm 99% sure this was fixed already.
