### ISSUE TITLE
Exception on exporting __E102_OBJECTS/13.sa1mdl

### ISSUE THREAD

**Issue by Shadowth117** [sonicretro/sa_tools#64]
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at SonicRetro.SAModel.SAEditorCommon.Import.AssimpStuff.AssimpExport(NJS_OBJECT obj, Scene scene, String[] texInfo, Node parent, Int32& mdlindex) in E:\Programs\sa_tools\SAEditorCommon\Import\AssimpStuff.cs:line 376
   at SonicRetro.SAModel.SAMDL.MainForm.aSSIMPExportToolStripMenuItem_Click(Object sender, EventArgs e) in E:\Programs\sa_tools\SAMDL\MainForm.cs:line 1752
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by MainMemory** [comment]
The model itself has an invalid texture index, which isn't a problem ingame as it's animated.
