### ISSUE TITLE
SA2: SplitEvent fails to split certain cutscenes

### ISSUE THREAD

**Issue by End-User-Person** [sonicretro/sa_tools#79]
Attempting to use SplitEvent with cutscene files that have a scene with no model entities (e0203 is an example) will cause the process to stop and display the following error message. This also happens with cutscenes that utilize GC models (e0003, e0014, e0028, etc.)

```
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at splitEvent.Program.Main(String[] args) in E:\Programs\sa_tools\splitEvent\Program.cs:line 134
```

**Comment by MainMemory** [comment]
I can't really fix the GC models until I know how they work.
